### ISSUE TITLE
Control-+ should accept numpad and unshifted equals key

### ISSUE THREAD

**Issue by pshaughn** [asiekierka/zeta#1]
Most programs that accept control-+ implicitly also accept control-=, so you don't have to hold down shift to make it a plus sign; Zeta should do likewise. Relatedly, the numpad + and - don't do anything. (beta 24, windows 64-bit)

**Comment by asiekierka** [comment]
Thank you for the suggestion! I don't have a numpad on any of my keyboards (never really used them before), thus why it didn't occur for me to test that.
