### ISSUE TITLE
navigator.getGamepads requires HTTPS

### ISSUE THREAD

**Issue by DrDos0016** [asiekierka/zeta#11]
On recent versions of Firefox Zeta will not run if the connection isn't secure, throwing "Uncaught TypeError: navigator.getGamepads is not a function". This is because FF is now only exposing the gamepad over HTTPS connections. I'm unsure if other browsers are intending to do the same restriction.

This should probably be mentioned in any documentation with gamepad support being removed for unsecure connections.

Both Itch and the Museum of ZZT only serve content over HTTPs so this won't break anything there.

**Comment by asiekierka** [comment]
Fixed in https://github.com/asiekierka/zeta/commit/acff0c075f9ec01befe94a0d4d547f4047269570 - you've received an update for the Museum already (check repo issue tracker), I'll push out beta36 more widely eventually.
