### ISSUE TITLE
Building on Linux fails with "‘S_IFDIR’ undeclared" since beta38

### ISSUE THREAD

**Issue by rueter37** [asiekierka/zeta#14]
Building on Linux using Autotools fails since beta38. beta37 works for me. The OS I'm using is Lubuntu 20.04 and the compiler is GCC 9.3. Adding `#include "config.h"` in [line 22 of posix_vfs.c](https://github.com/asiekierka/zeta/blob/master/src/posix_vfs.c#L22) fixes the issue for me but I don't know if this is the right way to fix this issue. Below the build output:

`make  all-am`
`make[1]: Verzeichnis „/home/marcel/Downloads/Zeta/zeta/build“ wird betreten`
`/usr/bin/python3 ../tools/font2raw.py ../fonts/pc_ega.png 8 14 a src/8x14.bin`
`/usr/bin/python3 ../tools/font2raw.py ../fonts/pc_cga.png 8 8 dbl src/8x8dbl.bin`
`gcc -DHAVE_CONFIG_H -I. -I..    -std=c11 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libpng16  -g -O2 -MT src/zeta-cpu.o -MD -MP -MF src/.deps/zeta-cpu.Tpo -c -o src/zeta-cpu.o `test -f 'src/cpu.c' || echo '../'`src/cpu.c`
`gcc -DHAVE_CONFIG_H -I. -I..    -std=c11 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libpng16  -g -O2 -MT src/zeta-zzt.o -MD -MP -MF src/.deps/zeta-zzt.Tpo -c -o src/zeta-zzt.o `test -f 'src/zzt.c' || echo '../'`src/zzt.c`
`gcc -DHAVE_CONFIG_H -I. -I..    -std=c11 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libpng16  -g -O2 -MT src/zeta-zzt_ems.o -MD -MP -MF src/.deps/zeta-zzt_ems.Tpo -c -o src/zeta-zzt_ems.o `test -f 'src/zzt_ems.c' || echo '../'`src/zzt_ems.c`
`gcc -DHAVE_CONFIG_H -I. -I..    -std=c11 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libpng16  -g -O2 -MT src/zeta-audio_stream.o -MD -MP -MF src/.deps/zeta-audio_stream.Tpo -c -o src/zeta-audio_stream.o `test -f 'src/audio_stream.c' || echo '../'`src/audio_stream.c`
`mv -f src/.deps/zeta-zzt_ems.Tpo src/.deps/zeta-zzt_ems.Po`
`gcc -DHAVE_CONFIG_H -I. -I..    -std=c11 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libpng16  -g -O2 -MT src/zeta-audio_shared.o -MD -MP -MF src/.deps/zeta-audio_shared.Tpo -c -o src/zeta-audio_shared.o `test -f 'src/audio_shared.c' || echo '../'`src/audio_shared.c`
`mv -f src/.deps/zeta-audio_stream.Tpo src/.deps/zeta-audio_stream.Po`
`gcc -DHAVE_CONFIG_H -I. -I..    -std=c11 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libpng16  -g -O2 -MT src/zeta-util.o -MD -MP -MF src/.deps/zeta-util.Tpo -c -o src/zeta-util.o `test -f 'src/util.c' || echo '../'`src/util.c`
`mv -f src/.deps/zeta-audio_shared.Tpo src/.deps/zeta-audio_shared.Po`
`gcc -DHAVE_CONFIG_H -I. -I..    -std=c11 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libpng16  -g -O2 -MT src/zeta-asset_loader.o -MD -MP -MF src/.deps/zeta-asset_loader.Tpo -c -o src/zeta-asset_loader.o `test -f 'src/asset_loader.c' || echo '../'`src/asset_loader.c`
`mv -f src/.deps/zeta-util.Tpo src/.deps/zeta-util.Po`
`gcc -DHAVE_CONFIG_H -I. -I..    -std=c11 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libpng16  -g -O2 -MT src/zeta-posix_vfs.o -MD -MP -MF src/.deps/zeta-posix_vfs.Tpo -c -o src/zeta-posix_vfs.o `test -f 'src/posix_vfs.c' || echo '../'`src/posix_vfs.c`
`../src/posix_vfs.c: In function ‘vfs_process_entry’:`
`../src/posix_vfs.c:187:27: error: ‘S_IFDIR’ undeclared (first use in this function); did you mean ‘S_ISDIR’?`
`  187 |  if (entry_stat.st_mode & S_IFDIR) {`
`      |                           ^~~~~~~`
`      |                           S_ISDIR`
`../src/posix_vfs.c:187:27: note: each undeclared identifier is reported only once for each function it appears in`
`mv -f src/.deps/zeta-asset_loader.Tpo src/.deps/zeta-asset_loader.Po`
`gcc -DHAVE_CONFIG_H -I. -I..    -std=c11 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libpng16  -g -O2 -MT src/zeta-render_software.o -MD -MP -MF src/.deps/zeta-render_software.Tpo -c -o src/zeta-render_software.o `test -f 'src/render_software.c' || echo '../'`src/render_software.c`
`make[1]: *** [Makefile:700: src/zeta-posix_vfs.o] Fehler 1`
`make[1]: *** Auf noch nicht beendete Prozesse wird gewartet …`
`mv -f src/.deps/zeta-render_software.Tpo src/.deps/zeta-render_software.Po`
`mv -f src/.deps/zeta-zzt.Tpo src/.deps/zeta-zzt.Po`
`mv -f src/.deps/zeta-cpu.Tpo src/.deps/zeta-cpu.Po`
`make[1]: Verzeichnis „/home/marcel/Downloads/Zeta/zeta/build“ wird verlassen`
`make: *** [Makefile:377: all] Fehler 2`

**Comment by asiekierka** [comment]
Could you try with the latest commit?

**Comment by rueter37** [comment]
Thank you, your latest commit fixed this issue.
