### ISSUE TITLE
[REQUEST/ENHANCEMENT] Add EMS to Zeta's x86 emulation for some ZZT forks with EMS support.

### ISSUE THREAD

**Issue by TheRealHamtaro126** [asiekierka/zeta#4]
Since ZZO and I are the only ones talking about EMS support on a useful basis, Why not add it to Zeta to make it easy without having to use DOSBOX all the time, This will be a good step towards saving myself many an effort. Thanks for listening!!!

**Comment by asiekierka** [comment]
EMS, and mayhaps XMS, support is, indeed, planned. However, keep in mind that the deeper you go into using DOS features, the more likely it is that you'll be better served by DOSBox and fixing up the ZZT input code on its side - Zeta's design has limits, it was designed in a pre-Reconstruction world, and I don't want to just re-invent all of DOSBox.

**Comment by asiekierka** [comment]
By the way, I already made an EMS patch available [here](https://github.com/asiekierka/OpenZoo/blob/master/Patches/Enhancements/Use-EMS-memory-for-boards.patch) and Mr_Alert has an EMS/XMS patch [here](https://github.com/MrAlert/reconstruction-of-zzt/tree/extmem). You two are certainly not the only ones interested.

**Comment by asiekierka** [comment]
Needs some more work, but https://github.com/asiekierka/zeta/commit/c4508b617f64f32cb2b414dc13045b8766024853
