### ISSUE TITLE
Web only: Color 15 fg renders as pure white

### ISSUE THREAD

**Issue by computirman** [asiekierka/zeta#7]
In web zeta, color 15 foregrounds always render as pure white; Changes picked up with AX=1010h and AX=1012 reflect properly when white is the background color (with noblink on) or when the fg/bg are both white (color FF), but when color 15 is the foreground on a non-color 15 background, it renders as #ffffff.

**Comment by asiekierka** [comment]
More ZZT/Super ZZT assumptions...
